notifyOnSpigotRelease: true
notifyOnGitHubExperimentalRelease: false
loadPlantSettingsFromDatabase: false
enableDebugLog: false
activeSettingsPage: "default"
hibernateConfigPlantSettings:
  hibernate.connection.driver_class: "org.h2.Driver"
  hibernate.connection.url: "jdbc:h2:./plugins/ControlledPlantGrowth/data/plantSettings;AUTO_SERVER=TRUE"
  hibernate.hbm2ddl.auto: "update"
  hibernate.dialect: "org.hibernate.dialect.H2Dialect"
  hibernate.show_sql: "false"
  hibernate.connection.password: ""
  hibernate.connection.username: "sa"
hibernateConfigLocalPlantCache:
  hibernate.connection.driver_class: "org.h2.Driver"
  hibernate.connection.url: "jdbc:h2:./plugins/ControlledPlantGrowth/data/plantCache;AUTO_SERVER=TRUE"
  hibernate.hbm2ddl.auto: "update"
  hibernate.dialect: "org.hibernate.dialect.H2Dialect"
  hibernate.show_sql: "false"
  hibernate.connection.password: ""
  hibernate.connection.username: "sa"
currentSettingsVersion: "SETTINGS_V2"
