name: Spigot Versions CI

on:
  push:
  pull_request:
jobs:
  test-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spigot-version: ['1.21']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'

      - name: Build with Maven
        run: |
          mvn package
          ls
          pwd

      - name: Download BuildTools
        run: |
          mkdir buildtools
          curl -o buildtools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build Spigot server
        run: |
          cd buildtools
          java -jar BuildTools.jar --rev ${{ matrix.spigot-version }}
          mkdir -p ../spigot
          cp ./spigot-${{ matrix.spigot-version }}.jar ../spigot/spigot.jar
          cd ..

      - name: Copy plugin JAR
        run: |
          ls
          pwd
          mkdir -p ./spigot/plugins
          cp ./target/*.jar ./spigot/plugins/CPG.jar

      - name: Start Spigot server
        run: |
          ls
          pwd
          cd spigot
          echo "eula=true" > eula.txt
          java -Xms512M -Xmx1024M -jar spigot.jar nogui &
          SERVER_PID=$!
          echo $SERVER_PID > ../server_pid.txt

      - name: Wait for Spigot server to start
        run: |
          while ! grep -q ")! For help, type" spigot/logs/latest.log; do
            sleep 5
          done

      - name: Check if plugin loaded
        id: check-plugin
        run: |
          if grep -q "ControlledPlantGrowth is enabled!" spigot/logs/latest.log; then
            echo "Plugin loaded successfully."
            echo "::set-output name=result::passed"
          else
            echo "Plugin failed to load."
            echo "::set-output name=result::failed"
            exit 1

      - name: Stop Spigot server
        run: |
          SERVER_PID=$(cat ../server_pid.txt)
          kill $SERVER_PID