name: Spigot Versions CI

on:
  push:
  pull_request:
jobs:
  test-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spigot-version: ['1.8', '1.20', '1.21']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          corretto: 'corretto'

      - name: Build with Maven
        run: mvn package

      - name: Download BuildTools
        run: |
          mkdir buildtools
          curl -o buildtools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build Spigot server
        run: |
          cd buildtools
          java -jar BuildTools.jar --rev ${{ matrix.spigot-version }}
          mkdir -p ../spigot
          cp Spigot/Spigot-Server/target/spigot-${{ matrix.spigot-version }}.jar ../spigot/spigot.jar

      - name: Copy plugin JAR
        run: |
          mkdir -p spigot/plugins
          cp target/*.jar spigot/plugins/CPG.jar

      - name: Start Spigot server
        run: |
          cd spigot
          echo "eula=true" > eula.txt
          java -Xms512M -Xmx1024M -jar spigot.jar nogui &
          SERVER_PID=$!
          echo $SERVER_PID > ../server_pid.txt

      - name: Wait for Spigot server to start
        run: |
          while ! grep -q ")! For help, type" spigot/logs/latest.log; do
            sleep 5
          done

      - name: Check if plugin loaded
        id: check-plugin
        run: |
          if grep -q "ControlledPlantGrowth is enabled!" spigot/logs/latest.log; then
            echo "Plugin loaded successfully."
            echo "::set-output name=result::passed"
          else
            echo "Plugin failed to load."
            echo "::set-output name=result::failed"
            exit 1

      - name: Stop Spigot server
        run: |
          SERVER_PID=$(cat ../server_pid.txt)
          kill $SERVER_PID

  summary:
    runs-on: ubuntu-latest
    needs: [test-plugin]
    steps:
      - name: Create summary
        run: |
          echo "## Plugin Test Summary" > summary.md
          echo "" >> summary.md
          for version in 1.8 1.20 1.21; do
            if [[ "${{ needs.test-plugin.outputs.result }}" == "passed" ]]; then
              echo "- Spigot $version: **Passed**" >> summary.md
            else
              echo "- Spigot $version: **Failed**" >> summary.md
            fi
          done
          cat summary.md

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: Spigot Server Version Test Summary
          path: summary.md
