name: Spigot Versions CI

on:
  push:
  pull_request:
jobs:
  test-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spigot-version: ['1.21']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22 for Maven Build
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'

      - name: Build with Maven
        run: |
          mvn package
          ls
          pwd

      - name: Download BuildTools
        run: |
          mkdir buildtools
          curl -o buildtools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build Spigot server
        run: |
          cd buildtools
          java -jar BuildTools.jar --rev ${{ matrix.spigot-version }}
          mkdir -p ../spigot
          cp ./spigot-${{ matrix.spigot-version }}.jar ../spigot/spigot.jar
          cd ..

      - name: Copy plugin JAR
        run: |
          mkdir -p ./spigot/plugins
          cp ./target/controlledplantgrowth*[0-9].jar ./spigot/plugins

      - name: Start Spigot server
        run: |
          cd spigot
          echo "eula=true" > eula.txt
          java -Xms512M -Xmx1024M -jar spigot.jar nogui &
          SERVER_PID=$!
          echo $SERVER_PID > ./serverPid.txt
          echo "Started Spigot server with PID"
          echo $SERVER_PID

      - name: Wait for Spigot server to start
        run: |
          while ! grep -q ")! For help, type" spigot/logs/latest.log; do
            echo "Server not started yet ... waiting"
            sleep 5
          done

      - name: Check if plugin loaded
        id: check-plugin
        run: |
          if grep -q "ControlledPlantGrowth is enabled!" spigot/logs/latest.log; then
            echo "Plugin loaded successfully."
            echo "result=passed" >>$GITHUB_OUTPUT
          else
            echo "Plugin failed to load."
            echo "result=failed" >>$GITHUB_OUTPUT
          fi

      - name: Stop Spigot server
        run: |
          SERVER_PID=$(cat ./serverPid.txt)
          kill $SERVER_PID
          exit 0